### ISSUE TITLE
Cut next release (probably v1.43.1)

### ISSUE THREAD

**Issue by saschagrunert** [containers/storage#1426]
We have a huge amount of commits in the `main` branch from the previous release: https://github.com/containers/storage/compare/v1.43.0...main

Are we happy to cut a next version yet?

**Comment by rhatdan** [comment]
Whenever you want one, I am fine with cutting it.

**Comment by saschagrunert** [comment]
Thank you! Looking forward to the new release being part of CRI-O. :)

**Comment by rhatdan** [comment]
https://github.com/containers/storage/releases/tag/v1.44.0

**Comment by p0pr0ck5** [comment]
Hello,

This latest release (1.44.0) contains a [breaking change](https://github.com/containers/storage/pull/1399) in the API. Should this project move to a `v2`? It's not possible to compile applications that have `github.com/containers/podman/v4` as a dependency when the project `go.mod` includes `github.com/containers/storage@v1.44.0`, due to this change. Example output (I can provide more details if needed):

```
# github.com/containers/podman/v4/pkg/rootless
../../../go/pkg/mod/github.com/containers/podman/v4@v4.3.1/pkg/rootless/rootless.go:43:18: pidFileLock.Locked undefined (type lockfile.Locker has no field or method Locked)
```

This isn't a problem for the most recent tag of `github.com/containers/podman`, since it pins to `github.com/containers/storage@v1.43.0` (https://github.com/containers/podman/blob/v4.3.1/go.mod#L20), but I found that when running `go get -u` on a project that uses `github.com/containers/podman`, `github.com/containers/storage` was upgraded to `v1.44.0` and caused a compile failure. I had to manually change the indirect dependency pin to `github.com/containers/storage@v1.43.0` in my project `go.mod`.

If `github.com/containers/storage` is following semantic versioning, should the breaking API change result in a separate `v2` tag?

**Comment by chenrui333** [comment]
yeah, I have the similar question, as there is a breaking change in the API, it might be good to release as a major version update.

**Comment by rhatdan** [comment]
We are using this version of container/storage in main branch right now.  Are you saying Podman 4.4 has modified to use this API.
