### ISSUE TITLE
pkg/chunked/GetDiffer must differentiate between failures and errors that can be ignored

### ISSUE THREAD

**Issue by giuseppe** [containers/storage#2115]
we currently do not differentiate between critical errors (hard failures) and ignorable errors, so that the caller (containers/image in our case) can fallback to using the traditional pull code path.

Especially with composefs and fs-verity, if any error happens in this phase, the entire pull operation must fail and containers/image must not attempt any fallback.

Suggestion: define a new error typefor the errors that can be ignored and treat anything else as an hard failure, so that the caller can differentiate between them.

**Comment by giuseppe** [comment]
@mtrmac what do you think?

**Comment by mtrmac** [comment]
For context, what are the “ignorable” error situations? I can see:
- `c/image/internal/private.BadPartialRequestError` ~ `pkg/chunked/ErrBadRequest`: missing registry support
- `enable_partial_images` disabled
- layer is not chunked / missing TOC annotations.

And those are currently always ignorable, but might be fatal in an enforcing configuration, I guess.

Are there any _other_ significant classes of ignorable errors?

---

Yes, having a special error type (returned by `chunked.GetDiffer?`), and handling it specially in c/image so that other errors don’t trigger a fallback to the full layer copy, LGTM.

**Comment by giuseppe** [comment]
yes, the only "ignorable" errors are the ones where the image doesn't support partial pulls and there is no conversion enabled.  Missing registry support should be a hard error when `convert_images` is configured

**Comment by giuseppe** [comment]
thanks, opened a PR to implement it: https://github.com/containers/storage/pull/2118
