### ISSUE TITLE
Add reflinks suport to the vfs storage driver

### ISSUE THREAD

**Issue by robmv** [containers/storage#241]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind feature**

**Description**

In order to speed up rootless container creation using the vfs storage driver, it could be possible to use reflinks when available, for example over Btrfs or XFS (with reflink enabled format), when creating the container tree. The speed of container creation is one the drawbacks of the vfs driver, since it has to copy the entire tree, with reflinks this could be reduced significantly.

**Comment by rhatdan** [comment]
@giuseppe Done.

**Comment by sandeen** [comment]
The XFS developer community would welcome any and all reports of success or failure with this reflink usecase.  Reflink is not yet on by default; we roll out new features very carefullly and deliberately:

1. Experimental
2. Optional
3. Default

The more feedback and testing we get in step 2), the more quickly and confidently we can move to step 3).

**Comment by rhatdan** [comment]
sandeen we should turn it on in Rawhide so that you could get the feedback.  If there is no way for a mere mortal to turn it on, then it will not be tested.

I have been told that:

`mkfs.xfs in RHEL8 has enabled reflink by default since June 2018 / xfsprogs-4.17.0-1.el8`

So at least people playing with the Beta will be able to try it out, Now we need to fix containres/storage and get it merged into podman.

**Comment by sandeen** [comment]
> Now we need to fix containres/storage and get it merged into podman.

When you do that and have some testing under your belt, please let me know.

Thanks,
-Eric

**Comment by giuseppe** [comment]
done with 6c86fe70d3d66c2af054fade9a11bf54e8225673

**Comment by robmv** [comment]
Thanks to everyone involved
