### ISSUE TITLE
Add support for returning size and inodes for storage drivers

### ISSUE THREAD

**Issue by mrunalp** [containers/storage#292]
We need efficient way of returning number of inodes and size used by entire storage without having to walk the tree if possible. This is needed for the CRI ImageInfo call. 

@sboeuf

**Comment by rhatdan** [comment]
@rhvgoyal Any ideas?

du --inodes -s . 
du --sM .

Would seem to be the fastest way.

**Comment by rhatdan** [comment]
@nalind @mrunalp WDYT?

**Comment by rhatdan** [comment]
@mrunalp Do you need the size of the entire image or just the size of a layer?

**Comment by nalind** [comment]
Running `du` under `strace` suggests that it's simply walking the directory tree and `stat()`ing everything, so we might not gain much by calling out to `du` instead of implementing a walk ourselves.

It looks like CRI-O needs the information for filling out CRI's [`FileSystemUsage`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L1169) field in [`ContainerStats`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L1238), which can be requested either for a specific container or for every known container, to be returned as a list; and for stats in [`ImageFsInfoResponse`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L1238), though since the prototype for `FileSystemUsage`'s `FilesystemIdentifier` field says that it contains a mountpoint, I can't tell from it if each entry in that list signifies a particular image, or if each entry signifies a group of images stored together under a particular location.

**Comment by rhatdan** [comment]
@mrunalp Can you help answer @nalind questions?

**Comment by rhatdan** [comment]
Since there has been no movement on this  Issue by @mrunalp or @nalind I am going to close.  Please reopen if you feel we should work on this.
