### ISSUE TITLE
Improve overlay startup performance.

### ISSUE THREAD

**Issue by rhatdan** [containers/storage#368]
On every run of tools using container/storage overlay driver, we are running supportsOverlay function which does a whole bunch of processes in mounting of file systems.  Once this is done once we should not have to do it again until the next time the system boots.
       
Basically have driver create

/run/containers/storage/overlay/supportsDtype

/run/containers/storage/overlay/usingMetacopy

And then just do a gettattr on these files, if they exists, no reason to do the check.

Save each podman/buildah/cri-o/skopeo command from having to do them, after the first one in a boot.

**Comment by rhatdan** [comment]
@nalind WDYT?

**Comment by rhatdan** [comment]
@baude WDYT?

**Comment by vrothberg** [comment]
SGTM

**Comment by nalind** [comment]
metacopy is controlled by configuration, which can conceivably change between runs (eek!), so I'm not sure about caching it.  If the goal is to skip the tests when we can, we'd want to distinguish between enabled/disabled/haven't-checked-yet, otherwise it's still going to be slower on systems where one or both features aren't available.  Otherwise, yeah, it sounds fine.

**Comment by rhatdan** [comment]
Yes I was just thinking we would getattr on /run/containers/storage/overlay/metacopy, supportsDtype, overlay.
Then also check the date on the storage.conf file, if this is newer then the date on these files, then we recheck.

The reason we need this, is we are seeing tools like OpenStack that are constantly running podman commands, which take this hit on every start.  We see hangs in this code when doing  a podman inspect when the system is fully loaded.
