### ISSUE TITLE
overlay: mount counter checks for overlay, even if we're using fuse-overlayfs

### ISSUE THREAD

**Issue by nalind** [containers/storage#447]
When we're using `fuse-overlayfs`, we skip the is-supported test so that we can run on top of an overlay filesystem, but we may also skip mount attempts because when we ask the mount counter if a container's rootfs is mounted in `get()`, it returns true because that location is already on an overlay filesystem.

This is affecting people who try to run the `quay.io/buildah/stable:latest` image.

**Comment by rhatdan** [comment]
Do you have a proposed fix?

**Comment by nalind** [comment]
We can skip using the `ctr` field if `mountProgram` is set, or we can teach it to check for a different filesystem magic value for those cases, or @giuseppe may have another option to suggest.

**Comment by giuseppe** [comment]
I think checking for a different filesystem would be better.  I think it should be fine to assume it is a FUSE filesystem when `mountProgram` is used.

**Comment by rhatdan** [comment]
@giuseppe Could you open a PR for this?  I think this is one thing that will break podman in podman.

**Comment by nalind** [comment]
I'm okay with that, so long as it won't set up a problem for rootless-in-rootless, if we want to support that.  The magic value for FUSE is 0x65735546, FWIW.

**Comment by giuseppe** [comment]
PR opened here: https://github.com/containers/storage/pull/453

I've tested it manually, and verified that it is possible to use a storage on top of overlay for the storage directory.

> I'm okay with that, so long as it won't set up a problem for rootless-in-rootless

yes it will be a problem if we will want rootless-in-rootless, but for now it should not matter since fuse-overlayfs doesn't support running on top of fuse-overlayfs.

It could also be a problem if the storage directory is stored on top of another FUSE file system
