### ISSUE TITLE
many instances of 'size for layer $layer is unknown, failing getSize()'

### ISSUE THREAD

**Issue by haircommander** [containers/storage#569]
in CRI-O CI, we've been seeing tons of a warning from containers/image. Here's one reference: https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3388/test_pull_request_crio_e2e_rhel/11081/artifacts/journals/crio.service I've seen others, but I don't remember where they are. if I find another, I'll post it
(you can also ignore the segfault, that's already being addressed). 

Is there anything that would cause this at a particularly high frequency/anything we can do to mitigate it? I have no reason to believe it's causing any actual failures yet

**Comment by rhatdan** [comment]
Could you be asking for the size of a layer that has been deleted?

**Comment by rhatdan** [comment]
This is the function in containers/image
```

// getSize() adds up the sizes of the image's data blobs (which includes the configuration blob), the
// signatures, and the uncompressed sizes of all of the image's layers.
func (s *storageImageSource) getSize() (int64, error) {
	var sum int64
	// Size up the data blobs.
	dataNames, err := s.imageRef.transport.store.ListImageBigData(s.image.ID)
	if err != nil {
		return -1, errors.Wrapf(err, "error reading image %q", s.image.ID)
	}
	for _, dataName := range dataNames {
		bigSize, err := s.imageRef.transport.store.ImageBigDataSize(s.image.ID, dataName)
		if err != nil {
			return -1, errors.Wrapf(err, "error reading data blob size %q for %q", dataName, s.image.ID)
		}
		sum += bigSize
	}
	// Add the signature sizes.
	for _, sigSize := range s.SignatureSizes {
		sum += int64(sigSize)
	}
	// Walk the layer list.
	layerID := s.image.TopLayer
	for layerID != "" {
		layer, err := s.imageRef.transport.store.Layer(layerID)
		if err != nil {
			return -1, err
		}
		if layer.UncompressedDigest == "" || layer.UncompressedSize < 0 {
			return -1, errors.Errorf("size for layer %q is unknown, failing getSize()", layerID)
		}
		sum += layer.UncompressedSize
		if layer.Parent == "" {
			break
		}
		layerID = layer.Parent
	}
	return sum, nil
}

// Size() adds up the sizes of the image's data blobs (which includes the configuration blob), the
// signatures, and the uncompressed sizes of all of the image's layers.
func (s *storageImageSource) Size() (int64, error) {
	return s.getSize()
}

// Size() returns the previously-computed size of the image, with no error.
func (s *storageImageCloser) Size() (int64, error) {
	return s.size, nil
}

// newImage creates an image that also knows its size
func newImage(ctx context.Context, sys *types.SystemContext, s storageReference) (types.ImageCloser, error) {
	src, err := newImageSource(ctx, sys, s)
	if err != nil {
		return nil, err
	}
	img, err := image.FromSource(ctx, sys, src)
	if err != nil {
		return nil, err
	}
	size, err := src.getSize()
	if err != nil {
		return nil, err
	}
	return &storageImageCloser{ImageCloser: img, size: size}, nil
}
```
@mtrmac Ideas?

**Comment by rhatdan** [comment]
Basically we have a layer with
		if layer.UncompressedDigest == "" || layer.UncompressedSize < 0 {

**Comment by mtrmac** [comment]
We have traced this (in a different instance than the log above) to a `layers.json` like
```json
  {
    "id": "…",
    "created": "…",
    "flags": {
      "incomplete": true
    }
  },
```

an in-progress state recorded by c/storage while creating a layer. Such layers should be automatically cleaned up on restart, and it’s unknown why they aren’t.

**Comment by rhatdan** [comment]
Restart of what?  CRI-O?  The host?

**Comment by mtrmac** [comment]
“Start of any program using c/storage with the same store” (with write privileges? configured to use the store not read-only?) I don’t fully understand the situation — but restart of CRI-O should be sufficient.

**Comment by rhatdan** [comment]
Ok, but the issue is cri-o is seeing these images while running before being shut down.  And then generating log messages.  Can we judge when these situations happen and then not generate the log message?

**Comment by mtrmac** [comment]
- The _log message_ is not the problem, we can’t make the problem go away by just not logging it. The problem is:
  - We deduplicate layers by generating predictable IDs; if the ID for a necessary layer is “occupied” by an incomplete layer, we can’t very well just carry on (well, we could give up on deduplication, but really that’s not a fix for the underlying bug, which might be severe).
  - We don’t have a reason to try clean-up at the time of the log message AFAICS: Incomplete layers should never exist during ordinary runtime because they should have been cleaned up. If we are at “ordinary runtime” but the cleanup somehow didn’t happen (and didn’t fail!), I can’t see why we should expect a cleanup at that time to work (if it can even be done with concurrent c/storage users, no idea).
- It should be not possible for this to happen during one process lifetime: the error path is supposed to clear the incomplete layer, this should only exist on abnormal termination that prevents the cleanup.
- Looking at the log above, the first instance of the error is Mar 19 15:28:54, but CRI-O has panicked on Mar 19 15:28:21 . So, this is so far consistent with a crash causing incomplete layers to be left around, and a restart failing to clean them up.

**Comment by rhatdan** [comment]
@haircommander Is this still an issue?

**Comment by haircommander** [comment]
I can't remember seeing it recently, but I also don't know if anything has been done to fix it. Though, it doesn't sound like something that's high priority--it's not causing failures, but rather revealing failures that were encountered (a previous crash, in that example). If I run into it again, I will post more here, but I imagine it'd be fine if we closed this because there's no intention of fixing it
