### ISSUE TITLE
CRI-O should work out of the box on btrfs

### ISSUE THREAD

**Issue by cmurf** [containers/storage#929]
Right now it defaults to the overlay driver and btrfs needs to be enabled manually in storage.conf.

* autodetect when on btrfs, and use the btrfs driver; otherwise use overlay driver
* consider the case of upgrades, where overlay is already being used and overlay driver should continue being used

[Fedora btrfs issue](https://pagure.io/fedora-btrfs/project/issue/47)

**Comment by vrothberg** [comment]
Thanks!

@giuseppe @rhatdan what do you think?

**Comment by giuseppe** [comment]
the btrfs is not well maintained and it lacks some features we have on overlay.  I think overlay is still a better default also on btrfs

**Comment by Conan-Kudo** [comment]
Do you know what we're missing? Maybe we can figure out something to drive some development toward that.

(cc: @davide125)

**Comment by giuseppe** [comment]
The BTRFS driver can be a valid alternative if for any reason overlay is not available, but IMO overlay still works better for the containers storage and we should try to use it whenever it is possible.

BTRFS works fine as backing store for the overlay driver, so I'd like to know if there is any particular reason for preferring it instead of overlay.  Is there any use case where it works better than overlay?



overlay works fine with btrfs as backing store.

**Comment by cmurf** [comment]
Btrf snapshot creation and destruction is significantly more performant than reflink copies and unlinkat() for teardown. In theory the native driver should be less complicated.

I'm not finding issues reported against containers/btrfs driver or even the moby one. But certainly having resources to maintain the driver properly is a prerequisite for setting the native driver as default.

**Comment by rhatdan** [comment]
The issue is that Everyone in the world has been using Overlay, we have been working on overlay for many years and most of the core developers understand Overlay.  Almost noone in the world has used BTRFS in Podman, CRI-O, Buildah Docker or Containerd.  Would it work, probably.  Would it work as well?  In Rootless Mode?  What happens if the system default is BTRFS but the homedirs are not? On NFS?

I see little value in changing the default, and much risk.   If anything this should have been an issue in CRI-O.  Currently Containers/storage does very little shifting of storage.conf.

**Comment by cmurf** [comment]
I'll open an issue wherever it should go. I don't know the whole history of the btrfs driver, if it was direct copy or port from docker, but it got quite a lot of work back then initially, because that's what CoreOS was using by default.

Today with podman, it does work rootless same as rootful, for subvolume/snapshot creation and teardown. There is a fallback to (effectively) use rm -rf if the btrfs file system is not mounted with `user_subvol_rm_allowed` option (this mount option is not used by default, thus the fallback is the default). So it's either no different from overlay driver, which also does such a teardown, or it uses the much more efficient and non-blocking subvolume/snapshot delete.

However, there are valid questions about what happens when a container path is populated as "overlay" but the storage.conf is switched to btrfs driver (or vice versa) without doing a 'podman system reset'. My experience is confusion ensues, where all the earlier containers are present in the file system but are invisible to podman. I also don't know whether there's automatci fallback to overlay driver if the storage.conf says use btrfs but the container dir is not on btrfs. Elsewhere, the explanation has been that people using containers know what they are doing, so this kind of behavior is just not a high priority to tidy up. OK, but if there were ever to be a change in default driver, things need to be tidier for the general case. But in particular for upgrades. If upgrades were to switch drivers without better behavior, it'd be a bad experience.

I think one of two things should be true:

a. Support mixed driver setups properly, rather than switching drivers resulting in the containers for the other driver just vanishing (they are still present in the file system but they don't appear at all as far as podman is concerned). I can't assess if there's use cases for mixed driver setups. But maybe there are some kinds of workloads that create/destroy containers quickly and would be more performant with Btrfs; whereas there are other workloads that do a lot of page cache sharing which favors overlayfs. But this strikes me as hypothetical for now.

b. Only use the storage.conf specified driver for initially setting up a container path, i.e. if that path is in a reset state, use the storage.conf setting for initial population. If the container path is "overlayfs" then keep using that even if storage.conf says btrfs. If the container path is "btrfs" then keep using that even if storage.conf says overlay. This approach suggests preventing the user from falling into the trap in the first place, and probably isn't that difficult to implement compared to (a).

So if that discussion should be on cri-o/cri-o then I can do that.

**Comment by giuseppe** [comment]
since we are discussing also Podman, I think it is fine to keep the discussion here instead of the CRI-O issues tracker.

If there is any particular workload where btrfs performs better, then the users can select the btrfs driver in their config file, but that should not be the default.  In addition to what Dan said, I am still convinced that overlay is a better default even when btrfs is available, since all our development and maintenance efforts go in that direction.
